### ISSUE TITLE
Messing with layout

### ISSUE THREAD

**Issue by Pinkeltje** [conseilgouz/AutoReadMore-J4#11] opened 2024-05-16 14:04 UTC
Joomla 5.1
First of all many thanks for developing this plugin. Unfortunately I've encountered some issues: 

When using the plugin (I've used Gruz's plugin in J3, so copied settings), sidebar is pushed to the bottom (in Yootheme) and to the top (in Cassiopeia - sidebar right). 
Furthermore when there is bold text within the limit of the number of words, date is rendered bold as well.
For reference J3 site which is ok: []https://bergenlimburgonline.nl/
**Sidebar pushed to top in Cassiopeia**
![2024-05-16 Screenshot 350](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/276d2e2e-8c92-43dd-980a-8144860a8ba2)

**Sidebar pushed to bottom in Yootheme Pro**
![2024-05-16 Screenshot 351](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/1391755c-e798-4a82-9814-497403647bfa)

**Bold text for date**
![2024-05-16 Screenshot 352](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/bb15430a-7acb-47d0-8c65-48af07b174ac)

Dev site is on localhost, so unable to provide a link.

**Comment by conseilgouz** [comment] 2024-05-16 14:26
Hi Astrid,

Thank you for your message.

If you disable Autoreadmore plugin, is your site's layout correct ?

Could you send me a screenshot of Autoreadmore parameters ?

Regards,

Pascal

**Comment by Pinkeltje** [comment] 2024-05-16 15:06
Hi Pascal,

Thank you for you quick response. 
**Yes, Layout is correct when disabling plugin.**
![2024-05-16 Screenshot 354](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/58adf51c-1ea2-4a48-b00c-af6aaf7fc59b)

**Screenshots from Gruz's plugin settings on J3 site (working)**
![2024-05-16 Screenshot 359](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/10c0d4bd-ee12-431b-a3fb-8203b8f30905)
![2024-05-16 Screenshot 360](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/29ef021f-6999-4b37-85d4-6f04b5862828)

**Actual screenshots from your plugin settings**

![2024-05-16 Screenshot 357](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/3f45c56e-cb01-46b0-8da8-23d1d4879d6a)
![2024-05-16 Screenshot 358](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/6323dda0-4499-4a7c-b5b2-c5dbde8bc205)


Furthermore Gruz's plugin took full article image when no intro image present and yours doesn't unfortunately. Tested with Cassiopeia and Yootheme Pro.

**J3 version:**
![2024-05-16 Screenshot 362](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/6e6c2b91-d348-4864-9a6e-858802398cce)

**Your version:**
![2024-05-16 Screenshot 361](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/9d5a5dfe-c7d3-410c-913b-ba49a2d7229f)

Thanks for looking into this.

**Comment by conseilgouz** [comment] 2024-05-16 16:12
Hi again,

I just put back htmLawed library which cleans up code when truncation is performed.

That's in new version 5.2.2.

Let me know if it solves your issues.

Pascal

**Comment by conseilgouz** [comment] 2024-05-16 16:17
Oups, I forgot to copy htmlLawed library in Helper directory.
That's done, version 5.2.3 is now available.
Pascal

**Comment by Pinkeltje** [comment] 2024-05-16 16:25
Thx! Will have a look tomorrow. Will check Dutch translation as well as it appears to be machine translation (Google or Deepl) and therefore sometimes confusing. Had to set my backend language to English to understand ;-)

**Comment by conseilgouz** [comment] 2024-05-16 18:09
I did not touch languages files, they are coming from J3 version. Gruz added a lot of language files when I prefer providing english and french ones for my extensions.
You are more than welcome to propose your Dutch language file.

**Comment by Pinkeltje** [comment] 2024-05-17 09:01
Hi Pascal,

Please find attached new Dutch language files. 
Patch is working now for page layout (sidebar is where it should be), but still no full article image shown when no intro image is present in Images and links.  Plugin neatly pulls image that is inserted manually in article and image class is working also.
[NL_plg_content_autoreadmore.zip](https://github.com/conseilgouz/AutoReadMore-J4/files/15346565/NL_plg_content_autoreadmore.zip)

**Comment by conseilgouz** [comment] 2024-05-17 09:24
Hi,

Thank you for NL language files. I'll release them as soon as possible.

About, full article image, I just made a try and it seems OK. I used your parameters.

I'm making some more tries and let you know if I can reproduce this.

Pascal

**Comment by conseilgouz** [comment] 2024-05-18 11:27
Hello Astrid,
I was not able to reproduce your full image issue.
How is created your article ? what code does it contain ? 
According to the plugin's code, it's looking for the first img tag if no introduction image exists. Are you using a plugin to display your image (like responsive image plugin from Grammatiko) ? In this case, images are not in an img tag but using picture / srcset tags.

Pascal

**Comment by Pinkeltje** [comment] 2024-05-19 06:39
Hi Pascal,

Really don't understand it.
Screenshots from clean Joomla 5 install with Cassiopeia.

**Intro on homepage:**
![2024-05-19 Screenshot 364](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/2de14178-4dae-4c88-8c5c-3ca0dc837ffb)

**Full article**
![2024-05-19 Screenshot 365](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/3abd81b9-2f81-4c04-a18a-51953658dd22)

Astrid

**Comment by conseilgouz** [comment] 2024-05-19 08:18
Thank you Astrid for telling me about the notice. 
I use this plugin with Joomla 4 & joomla 5 sites, but, I don't use Cassiopeia template.
I'm doing some more testings and let you know if I can reproduce your issue with a J510 clean install.
Pascal

**Comment by Pinkeltje** [comment] 2024-05-19 09:03
I normally use Yootheme Pro template. But decided to test with everything default to eliminate any conflicts with extensions or templates.

**Comment by conseilgouz** [comment] 2024-05-19 09:17
Hi again,
I just installed a clean J510, used the examples data.
I created a new article and everything is fine.
If you disable Autoreadmore plugin and add a readmore in your article, is your image displayed ?
If not, it must be an article or menu parameter error. 
Pascal
![autoreadmore_article](https://github.com/conseilgouz/AutoReadMore-J4/assets/19435246/0cc9c9c8-3274-4c8b-a12c-9442dccd4cba)

![autoreadmore_article_debug](https://github.com/conseilgouz/AutoReadMore-J4/assets/19435246/d5b6d6fd-19d8-4ab8-b5a0-82b2ad3702db)

**Blog display**

![autoreadmore_feature](https://github.com/conseilgouz/AutoReadMore-J4/assets/19435246/1c422c1d-b2c0-49ae-b24b-0f3d24f01c7f)

**When clicking on readmore button, full article display** 

![autoreadmore_site](https://github.com/conseilgouz/AutoReadMore-J4/assets/19435246/91d304fc-2952-4ee7-acab-f4d84e91a0ae)

**Comment by Pinkeltje** [comment] 2024-05-19 09:56
I think there is a misunderstanding.
You are having your image inside the article. That works for me also. But my problem is with the image inserted through the Images and Links tab, when only having a full article image.
Hope the link to the J3 site and the screenshots clarifies my issue. J5 site is on localhost, so unable to provide a link.

I'm updating a Joomla 3 site with Gruz's plugin
[]https://t.ly/JgbCg

![2024-05-19 Screenshot 370](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/24206015-4e5a-4602-809e-958d783b74c4)

After the update and using your version of the plugin, this isn't working anymore.

![2024-05-19 Screenshot 373](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/de5308ba-f9eb-48a0-b05d-678842388ce0)

![2024-05-19 Screenshot 371](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/4a34fa62-ecfb-4392-b91e-8d30296799df)

**Comment by conseilgouz** [comment] 2024-05-19 12:18
Ok, I see.

The problem is that, to work, the plugin should call image_fulltext, but it does not, and never did : I checked in the previous versions and could not find this.

I think it's normal as image_intro is to be displayed in blog/feature modes when image_fulltext will be when the whole article is displayed.

Even if it does not make sens, I think I'll work on this as you set "force image count" parameter to 1, which means "find any image in my article".

I'll let you know as soon it's available.

Pascal

**Comment by conseilgouz** [comment] 2024-05-19 13:14
Hi again,

Version 5.2.5 implements "use fulltext image if no other image can be found".

Let me know if this closes the current issue.

Pascal

**Comment by Pinkeltje** [comment] 2024-05-19 13:53
Hi Pascal,

>The problem is that, to work, the plugin should call image_fulltext, but it does not, and never did : I checked in the previous versions and could not find this.

Was looking for that in old plugin as well, and couldn't find it either. That's why it's so strange that it worked with Gruz's version....

But the good news is that it works like a charm now. Thanks a lot, merci beaucoup, for your hard work.

Astrid

![2024-05-19 Screenshot 374](https://github.com/conseilgouz/AutoReadMore-J4/assets/8941310/5824455f-ce36-4e4e-a01f-6552a94b1fe7)

**Comment by conseilgouz** [comment] 2024-05-19 13:55
issues solved by version 5.2.4 & 5.2.5

**Closed as completed by conseilgouz** 2024-05-19 13:55 UTC
